spring:
  data:
    mongodb:
      fileDBUri: mongodb://homework:123456@localhost:27017/file
      dataDBUri: mongodb://homework:123456@localhost:27017/data
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data-source:
    homework:
      jdbc-url: jdbc:h2:mem:homework;MODE=MYSQL;INIT=RUNSCRIPT FROM './src/componentTest/resources/initdb/init-homework-db.sql'
      username: sa
      driver-class-name: org.h2.Driver
    education:
      jdbc-url: jdbc:h2:mem:education;MODE=MYSQL;
      username: sa
      driver-class-name: org.h2.Driver