server:
  port: 802

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      fileDBUri: mongodb://homework:123456@localhost:27017/file
      dataDBUri: mongodb://homework:123456@localhost:27017/data
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB