server:
  port: 802
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      fileDBUri: mongodb://root:123456@localhost:27017/file
      dataDBUri: mongodb://root:123456@localhost:27017/data