server:
  port: 802

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      fileDBUri: mongodb://homework:123456@localhost:27017/file
      dataDBUri: mongodb://homework:123456@localhost:27017/data
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data-source:
    homework:
      url: jdbc:mysql://localhost:3306/test1
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    education:
      url: jdbc:mysql://localhost:3306/test1
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver