server:
  port: 802

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      fileDBUri: mongodb://homework:123456@localhost:27017/file
      dataDBUri: mongodb://homework:123456@localhost:27017/data
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  data-source:
    homework:
      jdbc-url: jdbc:mysql://localhost:3306/homework
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    education:
      jdbc-url: jdbc:mysql://localhost:3306/education
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: homework-service
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  zipkin:
    rabbitmq:
      queue: sleuth
    sender:
      type: rabbit

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:803/eureka/
  instance:
    prefer-ip-address: true

education:
  rabbit:
    publishX: education_homework_event