version: "3"
services:
  mongoDB:
    restart: always
    container_name: ztlsir-homework-mongodb-test
    image: mongo
    networks:
      local_net:
        ipv4_address: 172.18.0.3
    ports:
      - 27016:27017
    environment:
      MONGO_INITDB_DATABASE: file
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo/initdb/:/docker-entrypoint-initdb.d/:ro

networks:
  local_net:
    external:
      name: lan